package org.projEuler;

import java.util.logging.Level;
import java.util.logging.Logger;

/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1,2,3,5,8,13,21,34,55,89,...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */


class EvenFibonacciNumbers {
    static final Logger logger = Logger.getLogger(EvenFibonacciNumbers.class.getName());

     static void fibo(int N) {
        int output = 0;
        int newsum = 1;
        int totalsum = 0;
        for (int i = 0; i < N; i++) {

            logger.log(Level.INFO, "The fibo is: {0}", output);
            int num3 = newsum + output;
                if (num3 % 2 == 0) {
                    totalsum = totalsum + num3;
                }
            output = newsum;
            newsum = num3;

            }
        logger.log(Level.INFO, "The total sum of all even Fibonacci numbers is: {0} ", totalsum);
        }


    public static void  main(String args[]) {
    //Call fibo
        fibo(100);
    }
}

